[package]
name = "advent-of-code-24"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
env_logger = "0.11.5"
indicatif = "0.17.9"
instant = "0.1.13"
log = "0.4.22"
rayon = "1.10.0"
regex = "1.11.1"
